const chatDetail1 = [
  {
    messageID: 10,
    senderID: 1,
    senderName: "John Doe",
    content: "Later!",
    date: "01/01/2024",
    time: "10:45",
  },
  {
    messageID: 9,
    senderID: 2,
    senderName: "Jane Smith",
    content: "Alright, gotta go, talk to you guys later",
    date: "01/01/2024",
    time: "10:40",
  },
  {
    messageID: 8,
    senderID: 111,
    senderName: "Ilham",
    content: "Yeah, same here",
    date: "01/01/2024",
    time: "10:35",
  },
  {
    messageID: 7,
    senderID: 1,
    senderName: "John Doe",
    content: "Just catching up, you know",
    date: "01/01/2024",
    time: "10:30",
  },
  {
    messageID: 6,
    senderID: 2,
    senderName: "Jane Smith",
    content: "Hey guys, what's going on?",
    date: "01/01/2024",
    time: "10:25",
  },
  {
    messageID: 5,
    senderID: 111,
    senderName: "Ilham",
    content: "Ah nice, where did you go?",
    date: "01/01/2024",
    time: "10:20",
  },
  {
    messageID: 4,
    senderID: 1,
    senderName: "John Doe",
    content: "Not much, just got back from lunch",
    date: "01/01/2024",
    time: "10:15",
  },
  {
    messageID: 3,
    senderID: 2,
    senderName: "Jane Smith",
    content: "Hey, what's up?",
    date: "01/01/2024",
    time: "10:10",
  },
  {
    messageID: 2,
    senderID: 111,
    senderName: "Ilham",
    content: "I'm good, thanks! How about you?",
    date: "01/01/2024",
    time: "10:05",
  },
  {
    messageID: 1,
    senderID: 1,
    senderName: "John Doe",
    content: "Hello, how are you?",
    date: "01/01/2024",
    time: "10:00",
  },
];

export default chatDetail1;